on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache NPM modules
        uses: actions/cache@v1
        env:
          cache-name: node-modules-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-deploy-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deploy-${{ env.cache-name }}-
            ${{ runner.os }}-deploy-
            ${{ runner.os }}-

      - name: Cache favicons
        uses: actions/cache@v1
        env:
          cache-name: favicons-cache
        with:
          path: ${{ github.workspace }}/.favicons-cache
          key: ${{ runner.os }}-deploy-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-deploy-${{ env.cache-name }}-

      - name: Install NPM dependencies
        run: npm install

      - name: MTIME DEBUG A0a
        run: ls -la ${{ github.workspace }}/.favicons-cache

      - name: MTIME DEBUG A0b
        run: cut ${{ github.workspace }}/.favicons-cache/* -b 1-2048

      - name: MTIME DEBUG B0a
        run: stat --format='%.Y' ${{ github.workspace }}/src/favicons/favicon-4096x4096.png ${{ github.workspace }}/node_modules/cache-loader/dist/cjs.js ${{ github.workspace }}/node_modules/favicons-webpack-plugin/src/loader.js

      # Next two steps aim to keep file modification timestamps of all files
      # identical from one deploy to the next, to have Webpack consistently
      # determine whether it should preserve or invalidate its cache.
      # https://github.com/webpack/webpack/issues/10707#issuecomment-613245056

      - name: Change mtime of git managed file to respective their last commit time
        run: |
          git ls-tree -r --name-only HEAD | while read filename; do
            touch -amt "$(git log -1 --pretty="format:%ad" --date=format:%Y%m%d%H%M.%S $filename)" "$filename"
          done

      - name: Change mtime of files under node_modules to last commit time of package-lock.json
        run: |
          package_lock_mtime=$(git log -1 --pretty="format:%ad" --date=format:%Y%m%d%H%M.%S package-lock.json)
          find node_modules -type f -print0 | xargs -0 touch -mt $package_lock_mtime

      - name: MTIME DEBUG B1a
        run: stat --format='%.Y' ${{ github.workspace }}/src/favicons/favicon-4096x4096.png ${{ github.workspace }}/node_modules/cache-loader/dist/cjs.js ${{ github.workspace }}/node_modules/favicons-webpack-plugin/src/loader.js

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: MTIME DEBUG A1a
        run: ls -la ${{ github.workspace }}/.favicons-cache

      - name: MTIME DEBUG A1b
        run: cut ${{ github.workspace }}/.favicons-cache/* -b 1-2048

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: www.fasterdisco.com
